### ISSUE TITLE
data2seq

### ISSUE THREAD

**Issue by linhan0109** [invictus717/MetaTransformer#38]
Can you give a demo about how to use data2seq code?

**Comment by invictus717** [comment]
Please refer to [Data2Seq.py](https://github.com/invictus717/MetaTransformer/blob/97dcc28c456e15172dea6d252a12740cd3acbd47/Data2Seq/Data2Seq.py#L19C6-L19C6)

```python
From Data2Seq import Data2Seq

auto_tokenier = Data2Seq(modality='image',dim=768)

# or 
auto_tokenier = Data2Seq(modality='video',dim=768)

# or
auto_tokenier = Data2Seq(modality='time-series',dim=768)
```

**Comment by linhan0109** [comment]
Thank you for your reply, and i have another question whether data2seq process dont need the unified model, this model is for the result of data2seq?

**Comment by invictus717** [comment]
Currently, the Data2Seq module doesn't share the parameters across different modalities. Personally, I think that it would be very cool if the Data2Seq module could be unified by a single tokenizer model. Because modalities require distinct patterns to extract modality-effective token sequences. In our paper, we found the process of designing a unified tokenizer could start from the grouping->convolution->transformation process, yet we did not unify multimodal tokenizers.
